// <auto-generated />
namespace SurvApe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class surveyidforquestion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(surveyidforquestion));
        
        string IMigrationMetadata.Id
        {
            get { return "201603021517002_survey id for question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
